name: Storybook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with: 
          repository: phork/phorkit

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build storybook
        run: yarn build-storybook
        env:
          STORYBOOK_URL: https://phork.github.io/

      - name: Deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: master
          folder: build/storybook
          clean: true
          clean-exclude: |
            .github
            README.md
